hostnames:
  - supercacher.steq.it

service:
  type: ClusterIP
  clusterIP: "None"
  annotations: {}
  ports:
    pypi: 8080
    npm: 8081
    apt: 8082
    proxy: 8083

image:
  pullPolicy: Always
  tag: main
  repository: 129317782449.dkr.ecr.eu-west-1.amazonaws.com/supercacher

replicaCount: 1

affinity: {}
imagePullSecrets: []
nodeSelector: {}
tolerations: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}
podLabels: {}

externalSecrets: false

podDisruptionBudget: {}
extraEnv: []
# - name:  some_env_var
#   value: some value

podSecurityContext:
  fsGroup: 101
  runAsUser: 101
  runAsGroup: 101

securityContext:
  capabilities:
    drop:
    - ALL
    - CAP_NET_RAW
  readOnlyRootFilesystem: true
  allowPrivilegeEscalation: false

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""
  rules: []

## Probes
livenessProbe:
  enabled: true
  initialDelaySeconds: 10
  timeoutSeconds: 30
  failureThreshold: 6

readinessProbe:
  enabled: true
  initialDelaySeconds: 10
  timeoutSeconds: 3
  periodSeconds: 5

startupProbe:
  enabled: true
  initialDelaySeconds: 5
  periodSeconds: 5
  timeoutSeconds: 1
  successThreshold: 1
  failureThreshold: 5

## Set resource definitions
resources:
  requests:
    memory: 64M
    cpu: 100m
    ephemeral-storage: "100Mi"
  limits:
    memory: 128M
    cpu: 200m
    ephemeral-storage: "500Mi"

## Create ingress object
ingress:
  enabled: false
  class: nginx
  cert_issuer: ""
  annotations: {}

## Additional existing secrets to mount as env vars
existingSecrets: []
# - name: someSecret

# Enable datadog
datadog:
  enabled: false
  mountPath: /var/run/datadog
  unifiedServiceTagging: false

## Persist data to a persistent volume
persistence:
  enabled: false
  ## If defined, storageClassName: <storageClass>
  ## If set to "-", storageClassName: "", which disables dynamic provisioning
  ## If undefined (the default) or set to null, no storageClassName spec is
  ##   set, choosing the default provisioner.  (gp2 on AWS, standard on
  ##   GKE, AWS & OpenStack)
  ##
  storageClass: "-"
  accessMode: ReadWriteOnce
  size: 200Gi
  annotations: {}
