{{- if and $.Values.persistence.enabled (not $.Values.persistence.existingClaim) }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "supercacher.fullname" $ }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "supercacher.labels" $ | nindent 4 }}
  {{- with $.Values.persistence.annotations }}
  annotations:
    {{ toYaml . | nindent 4 }}
  {{- end }}
spec:
  accessModes:
  - {{ default "ReadWriteOnce" $.Values.persistence.accessMode | quote }}
  resources:
    requests:
      storage: {{ $.Values.persistence.size | quote }}
{{- with $.Values.persistence.storageClass }}
{{- if eq "-" . }}
  storageClassName: ""
{{- else }}
  storageClassName: {{ . | quote }}
{{- end }}
{{- end }}
{{- end }}
