{{- if $.Values.serviceAccount.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "supercacher.fullname" $ }}
  namespace: {{ $.Release.Namespace | quote }}
  labels:
    {{- include "supercacher.labels" $ | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "supercacher.fullname" $ }}
subjects:
- kind: ServiceAccount
  name: {{ template "supercacher.serviceAccountName" $ }}
  namespace: {{ $.Release.Namespace | quote }}
{{- end }}
