{{- if $.Values.serviceAccount.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "supercacher.fullname" $ }}
  namespace: {{ $.Release.Namespace | quote }}
  labels:
    {{- include "supercacher.labels" $ | nindent 4 }}
rules:
{{- toYaml $.Values.serviceAccount.rules | indent 2 }}
{{- end }}
