apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ template "supercacher.fullname" . }}
  labels:
    app.kubernetes.io/lastDeployTime: {{ now | date "20060102150405" | quote }}
    {{- include "supercacher.labels" . | nindent 4 }}
spec:
  refreshInterval: "0"
  secretStoreRef:
    name: tiqets-secret-store
    kind: ClusterSecretStore
  target:
    name: {{ template "supercacher.fullname" . }}
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
  {{- range $key, $value := $.Values.secrets }}
  - secretKey: {{ $key }}
    remoteRef:
      key: {{ $value }}
  {{- end }}
