apiVersion: v1
kind: Service
metadata:
  name: {{ include "supercacher.fullname" $ }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "supercacher.labels" $ | nindent 4 }}
  {{- with $.Values.service.annotations }}
  annotations:
    {{ toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ $.Values.service.type }}
  ports:
  - name: http-pypi
    port: 8080
    targetPort: 8080
    protocol: TCP
  - name: http-npm
    port: 8081
    targetPort: 8081
    protocol: TCP
  - name: http-apt
    port: 8082
    targetPort: 8082
    protocol: TCP
  {{- with $.Values.service.clusterIP }}
  clusterIP: {{ . }}
  {{- end }}
  selector:
    {{- include "supercacher.selectorLabels" $ | nindent 4 }}
