apiVersion: v1
kind: Service
metadata:
  name: {{ include "supercacher.fullname" $ }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "supercacher.labels" $ | nindent 4 }}
  {{- with $.Values.service.annotations }}
  annotations:
    {{ toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ $.Values.service.type }}
  ports:
  {{- range $portname, $portnumber := $.Values.service.ports }}
  - name: {{ printf "http-%s" $portname }}
    port: {{ $portnumber }}
    targetPort: {{ $portnumber }}
    protocol: TCP
  {{- end }}
  {{- with $.Values.service.clusterIP }}
  clusterIP: {{ . }}
  {{- end }}
  selector:
    {{- include "supercacher.selectorLabels" $ | nindent 4 }}
