{{- if $.Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
automountServiceAccountToken: {{ default false $.Values.serviceAccount.automountServiceAccountToken }}
metadata:
  name: {{ include "supercacher.serviceAccountName" $ }}
  labels:
    {{- include "supercacher.labels" $ | nindent 4 }}
  {{- with $.Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
